(axiom (X))
(production ((X))
	    ()
	    (F) ((++) (X)) (F) ((--) (X)) (++) (X))
(stochastic-production ((F) (F) < (F))
		       ()
		       (0.5 (THREEF))
		       (0.5 ((F) (E))))
(stochastic-production ((F))
	    	       ()
	    	       (0.5 (F) (F))
		       (0.5 (F) (F) (F)))